def calc_complex_numbers(element_1, element_2, operation):
    if operation == '-':
        return complex(element_1) - complex(element_2)
    elif operation == '+':
        return complex(element_1) + complex(element_2)
    elif operation == '*':
        return complex(element_1) * complex(element_2)
    elif operation == '/':
        return complex(element_1) / complex(element_2)
